id: PFFD20993
initial_creation_type: ocr
source_metadata:
  volumes:
    7b843de3354649f39536396f04341478:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: འཕགས་མ་ལྷ་མོ་སྒྲོལ་མ་བསྒོམ་པའི་ཆོ་ག་རྒྱས་པ།
      total_pages: 1648
      volume_number: 40
